/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  foundation: [
    'intro',
  ],
  about: ['about/intro','about/principles','about/getting-started','about/team'],
  documentation: [
    'intro',
    'design-principles',
    {
      type: 'category',
      label: 'Guia de estilo',
      items: [{ type: 'autogenerated', dirName: 'style-guide' }]
    },
    'changelog'
  ],
  components: ['components/button','components/link','components/checkbox'],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
